# Generated by Django 4.1.1 on 2023-01-19 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='easypaisa_in',
            old_name='easypaisa_balance',
            new_name='easypaisa_balance_in',
        ),
        migrations.RenameField(
            model_name='easypaisa_out',
            old_name='easypaisa_balance',
            new_name='easypaisa_balance_out',
        ),
        migrations.RenameField(
            model_name='jazzcash_in',
            old_name='jazzcash_balance',
            new_name='jazzcash_balance_in',
        ),
        migrations.RenameField(
            model_name='jazzcash_out',
            old_name='jazzcash_balance',
            new_name='jazzcash_balance_out',
        ),
    ]
