# Generated by Django 4.1.1 on 2023-01-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_qty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Easypaisa_in',
        ),
        migrations.DeleteModel(
            name='Easypaisa_out',
        ),
        migrations.DeleteModel(
            name='Jazzcash_in',
        ),
        migrations.DeleteModel(
            name='Jazzcash_out',
        ),
        migrations.AddField(
            model_name='sold_prduct',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_model',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
