# Generated by Django 4.1.1 on 2023-01-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_easypaisa_in_delete_easypaisa_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold_prduct',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
