# Generated by Django 4.1.1 on 2023-01-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_sold_prduct_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
