# Generated by Django 4.1.1 on 2023-01-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='countsoldProduct',
            field=models.IntegerField(default=0),
        ),
    ]
