# Generated by Django 4.1.5 on 2023-02-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_product_countsoldproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Easypaisa_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easypaisa_balance_in', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Easypaisa_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easypaisa_balance_out', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('profit', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jazzcash_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jazzcash_balance_in', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Jazzcash_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jazzcash_balance_out', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('profit', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
