# Generated by Django 4.1.5 on 2023-02-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_easypaisa_in_easypaisa_out_jazzcash_in_jazzcash_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='easypaisa_out',
            old_name='profit',
            new_name='charges',
        ),
        migrations.RenameField(
            model_name='jazzcash_out',
            old_name='profit',
            new_name='charges',
        ),
    ]
