# Generated by Django 4.1.5 on 2023-02-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_profit_easypaisa_out_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='easypaisa_in',
            name='total',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
